# Generated by Django 5.0.4 on 2024-04-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название новостей  ')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.CharField(max_length=1000, verbose_name='Ссылка на фото')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'новость баскетбол',
                'verbose_name_plural': 'новости баскетбол',
            },
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'новость футбол', 'verbose_name_plural': 'новости футбол'},
        ),
    ]
