# Generated by Django 5.0.4 on 2024-04-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_info_hokey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название команды  ')),
            ],
            options={
                'verbose_name': 'подписки юзеров',
                'verbose_name_plural': 'подписки юзеров',
            },
        ),
    ]
